package io.nekohasekai.sagernet.fmt.wireguard

import io.nekohasekai.sagernet.ktx.queryParameterPreservingPlus
import moe.matsuri.nb4a.SingBoxOptions
import moe.matsuri.nb4a.utils.Util
import moe.matsuri.nb4a.utils.listByLineOrComma
import okhttp3.HttpUrl.Companion.toHttpUrlOrNull

// wireguard://<privateKey>@host:port?publickey=&presharedkey=&address=&mtu=&reserved=#name
// as generated by 3x-ui and v2rayN; Hiddify uses the wg:// scheme. `dns` and `keepalive`
// have no bean field and are ignored.
fun parseWireGuardLink(link: String): WireGuardBean {
    val url = link.replaceFirst("wireguard://", "https://").replaceFirst("wg://", "https://").toHttpUrlOrNull()
        ?: error("invalid wireguard link")
    return WireGuardBean().apply {
        serverAddress = url.host
        serverPort = url.port
        name = url.fragment
        privateKey = url.username.takeIf { it.isNotBlank() } ?: error("missing private key")
        peerPublicKey = url.queryParameterPreservingPlus("publickey") ?: error("missing publickey")
        peerPreSharedKey = url.queryParameterPreservingPlus("presharedkey")
        localAddress = url.queryParameter("address")?.listByLineOrComma()?.joinToString("\n") {
            when {
                it.contains("/") -> it
                it.contains(":") -> "$it/128"
                else -> "$it/32"
            }
        }?.takeIf { it.isNotBlank() } ?: error("missing address")
        mtu = url.queryParameter("mtu")?.toIntOrNull()
        reserved = url.queryParameterPreservingPlus("reserved")
    }
}

fun genReserved(anyStr: String): String {
    try {
        val list = anyStr.listByLineOrComma()
        val ba = ByteArray(3)
        if (list.size == 3) {
            list.forEachIndexed { index, s ->
                val i = s
                    .replace("[", "")
                    .replace("]", "")
                    .replace(" ", "")
                    .toIntOrNull() ?: return anyStr
                ba[index] = i.toByte()
            }
            return Util.b64EncodeOneLine(ba)
        } else {
            return anyStr
        }
    } catch (e: Exception) {
        return anyStr
    }
}

fun buildSingBoxOutboundWireguardBean(bean: WireGuardBean): SingBoxOptions.Outbound_WireGuardOptions = SingBoxOptions.Outbound_WireGuardOptions().apply {
    type = "wireguard"
    server = bean.serverAddress
    server_port = bean.serverPort
    local_address = bean.localAddress!!.listByLineOrComma()
    private_key = bean.privateKey
    peer_public_key = bean.peerPublicKey
    pre_shared_key = bean.peerPreSharedKey
    mtu = bean.mtu
    if (bean.reserved!!.isNotBlank()) reserved = genReserved(bean.reserved!!)
}
