package xyz.nekobyte.nekobox.fmt.wireguard

import okhttp3.HttpUrl.Companion.toHttpUrlOrNull
import xyz.nekobyte.nekobox.NekoBox
import xyz.nekobyte.nekobox.R
import xyz.nekobyte.nekobox.SingBoxOptions
import xyz.nekobyte.nekobox.fmt.AbstractBean
import xyz.nekobyte.nekobox.fmt.KryoConverters
import xyz.nekobyte.nekobox.fmt.amneziawg.AmneziaWGBean
import xyz.nekobyte.nekobox.fmt.dnsServer
import xyz.nekobyte.nekobox.fmt.parseHostsAddress
import xyz.nekobyte.nekobox.fmt.parseHostsDomain
import xyz.nekobyte.nekobox.group.IniConfig
import xyz.nekobyte.nekobox.ktx.isIpAddress
import xyz.nekobyte.nekobox.ktx.queryParameterPreservingPlus
import xyz.nekobyte.nekobox.ktx.unwrapIPV6Host
import xyz.nekobyte.nekobox.ktx.wrapIPV6Host
import xyz.nekobyte.nekobox.utils.Util
import xyz.nekobyte.nekobox.utils.listByLineOrComma
import java.net.InetAddress

object WireGuardDnsMode {
    // The app's DNS settings resolve everything; the profile's DNS servers are only kept.
    const val APP = 0

    // The profile's DNS replaces the remote DNS while the profile is the selected one.
    const val ALL = 1

    // The profile's DNS resolves the listed domains whenever the profile runs.
    const val DOMAINS = 2
}

// Bounds for the variable-length settings. Imports, the editor and the config builder check
// them alike. A stored profile is one Room row, read through a 2 MiB CursorWindow.
internal const val MAX_WIREGUARD_PEERS = 256
internal const val MAX_WIREGUARD_ALLOWED_IPS = 16384
internal const val MAX_WIREGUARD_DNS_ENTRIES = 64
internal const val MAX_WIREGUARD_PROFILE_BYTES = 512 * 1024

private val fullTunnel = listOf("0.0.0.0/0", "::/0")

// wireguard://<privateKey>@host:port?publickey=&presharedkey=&address=&mtu=&reserved=&dns=&keepalive=#name
// as generated by 3x-ui and v2rayN; Hiddify uses the wg:// scheme. These links carry no
// AllowedIPs, which by their convention means a full tunnel.
fun parseWireGuardLink(link: String): WireGuardBean {
    val url = link.replaceFirst("wireguard://", "https://").replaceFirst("wg://", "https://").toHttpUrlOrNull()
        ?: error("invalid wireguard link")
    return WireGuardBean().apply {
        serverAddress = url.host
        serverPort = url.port
        name = url.fragment
        privateKey = url.username.takeIf { it.isNotBlank() } ?: error("missing private key")
        peerPublicKey = url.queryParameterPreservingPlus("publickey") ?: error("missing publickey")
        peerPreSharedKey = url.queryParameterPreservingPlus("presharedkey")
        localAddress = url.queryParameter("address")?.listByLineOrComma()?.joinToString("\n") {
            when {
                it.contains("/") -> it
                it.contains(":") -> "$it/128"
                else -> "$it/32"
            }
        }?.takeIf { it.isNotBlank() } ?: error("missing address")
        mtu = url.queryParameter("mtu")?.toIntOrNull()
        reserved = url.queryParameterPreservingPlus("reserved")
        url.queryParameter("keepalive")?.let { persistentKeepalive = parseKeepalive(it) ?: error("invalid keepalive") }
        url.queryParameter("dns")?.let { dns ->
            val (servers, domains) = splitWireGuardDns(listOf(dns))
            importedDnsServers = servers.joinToString("\n")
            importedDnsDomains = domains.joinToString("\n")
        }
        initializeDefaultValues()
        checkWireGuardLimits()
    }
}

fun genReserved(anyStr: String): String {
    try {
        val list = anyStr.listByLineOrComma()
        val ba = ByteArray(3)
        if (list.size == 3) {
            list.forEachIndexed { index, s ->
                val i = s
                    .replace("[", "")
                    .replace("]", "")
                    .replace(" ", "")
                    .toIntOrNull() ?: return anyStr
                ba[index] = i.toByte()
            }
            return Util.b64EncodeOneLine(ba)
        } else {
            return anyStr
        }
    } catch (e: Exception) {
        return anyStr
    }
}

/** Reserved bytes as base64 of exactly three bytes, or null. */
internal fun normalizeReserved(value: String): String? {
    val encoded = genReserved(value)
    val decoded = runCatching { Util.b64Decode(encoded) }.getOrNull() ?: return null
    return encoded.takeIf { decoded.size == 3 }
}

/** The host a DNS server entry dials, or null when the app cannot use the entry. */
internal fun dnsServerHost(entry: String): String? = try {
    dnsServer(entry, "dns-check", "dns-direct").server
} catch (_: IllegalArgumentException) {
    null
}

/**
 * wg-quick `DNS =` and share-link `dns` values: addresses and URLs are servers, anything else a
 * search domain.
 */
internal fun splitWireGuardDns(values: List<String>): Pair<List<String>, List<String>> {
    val (servers, domains) = values.flatMap { it.listByLineOrComma() }.partition { it.contains("://") || it.unwrapIPV6Host().isIpAddress() }
    require(servers.all { dnsServerHost(it) != null }) { "unsupported DNS server" }
    return servers to domains
}

/** wg-quick `PersistentKeepalive`: seconds, or `off`. */
internal fun parseKeepalive(value: String): Int? = if (value.trim().equals("off", ignoreCase = true)) 0 else value.trim().toIntOrNull()?.takeIf { it in 0..65535 }

/** An AllowedIPs entry as a prefix; a bare address is a single host, as in wg-quick. */
internal fun normalizeAllowedIP(entry: String): String? {
    val address = parseHostsAddress(entry.substringBefore('/')) ?: return null
    val maxBits = if (address.contains(':')) 128 else 32
    val bits = entry.substringAfter('/', "$maxBits").toIntOrNull()?.takeIf { it in 0..maxBits } ?: return null
    return "$address/$bits"
}

internal fun parseAllowedIPs(values: List<String>): List<String>? = values.flatMap { it.listByLineOrComma() }.map { normalizeAllowedIP(it) ?: return null }

/** `host:port`, with brackets around an IPv6 host. */
internal fun parseWireGuardEndpoint(value: String): Pair<String, Int>? {
    val host = value.trim().substringBeforeLast(':', "").unwrapIPV6Host().takeIf { it.isNotBlank() } ?: return null
    val port = value.trim().substringAfterLast(':').toIntOrNull()?.takeIf { it in 1..65535 } ?: return null
    return host to port
}

/**
 * One peer as a wg-quick `[Peer]` section. Each value must be a single token, so a value taken
 * from another format cannot add a line or a key, or start a comment.
 */
internal fun wireGuardPeerSection(
    publicKey: String,
    preSharedKey: String?,
    endpoint: Pair<String, Int>?,
    allowedIPs: List<String>,
    keepalive: Int,
    reserved: String? = null,
): String {
    val values = listOfNotNull(publicKey, preSharedKey?.ifEmpty { null }, endpoint?.first, reserved?.ifEmpty { null }) + allowedIPs
    require(values.all { value -> value.isNotEmpty() && value.none { it.isWhitespace() || it.isISOControl() || it == '#' } }) {
        "invalid peer value"
    }
    return buildString {
        appendLine("[Peer]")
        appendLine("PublicKey = $publicKey")
        if (!preSharedKey.isNullOrEmpty()) appendLine("PresharedKey = $preSharedKey")
        if (endpoint != null) appendLine("Endpoint = ${endpoint.first.wrapIPV6Host()}:${endpoint.second}")
        appendLine("AllowedIPs = ${allowedIPs.joinToString(", ")}")
        if (keepalive > 0) appendLine("PersistentKeepalive = $keepalive")
        if (!reserved.isNullOrEmpty()) appendLine("Reserved = $reserved")
    }
}

/** Number of `[Peer]` sections in the additional peers text. */
internal fun extraPeerCount(extraPeers: String): Int = if (extraPeers.isBlank()) 0 else IniConfig.parse(extraPeers).getAll("Peer")?.size ?: 0

/** The settings WireGuard and AmneziaWG profiles share. */
internal class WireGuardSettings(
    val name: String,
    val server: String,
    val port: Int,
    val publicKey: String,
    val preSharedKey: String,
    val reserved: String,
    val allowedIPs: String,
    val keepalive: Int,
    val extraPeers: String,
    val importedDnsServers: String,
    val importedDnsDomains: String,
    val dnsMode: Int,
    val customDnsServers: String,
    val customDnsDomains: String,
    val serverPeerPosition: Int,
) {
    // Blank overrides follow the imported values.
    val dnsServers get() = customDnsServers.ifBlank { importedDnsServers }
    val dnsDomains get() = customDnsDomains.ifBlank { importedDnsDomains }
}

internal fun AbstractBean.wireGuardSettings(): WireGuardSettings? = when (this) {
    is WireGuardBean -> WireGuardSettings(
        displayName(), serverAddress!!, serverPort!!, peerPublicKey!!, peerPreSharedKey!!, reserved!!,
        allowedIPs!!, persistentKeepalive!!, extraPeers!!, importedDnsServers!!, importedDnsDomains!!,
        dnsMode!!, customDnsServers!!, customDnsDomains!!, serverPeerPosition!!,
    )

    is AmneziaWGBean -> WireGuardSettings(
        displayName(), serverAddress!!, serverPort!!, peerPublicKey!!, peerPreSharedKey!!, reserved!!,
        allowedIPs!!, persistentKeepalive!!, extraPeers!!, importedDnsServers!!, importedDnsDomains!!,
        dnsMode!!, customDnsServers!!, customDnsDomains!!, serverPeerPosition!!,
    )

    else -> null
}

private fun string(id: Int, vararg args: Any) = NekoBox.application.getString(id, *args)

private fun WireGuardSettings.extraSections(): List<IniConfig.Section> {
    if (extraPeers.isBlank()) return emptyList()
    val ini = IniConfig.parse(extraPeers)
    // Text outside a [Peer] section would otherwise drop out without a word.
    require(!ini.hasUnrecognizedLines && ini.sectionNames().all { it.equals("Peer", ignoreCase = true) }) {
        string(R.string.wireguard_invalid_extra_peers, name)
    }
    return ini.getAll("Peer") ?: throw IllegalArgumentException(string(R.string.wireguard_invalid_extra_peers, name))
}

private fun WireGuardSettings.serverPeer(number: Int) = SingBoxOptions.WireGuardPeer().apply {
    server = this@serverPeer.server
    server_port = port
    public_key = publicKey
    pre_shared_key = preSharedKey
    allowed_ips = if (this@serverPeer.allowedIPs.isBlank()) {
        fullTunnel
    } else {
        parseAllowedIPs(listOf(this@serverPeer.allowedIPs))?.takeIf { it.isNotEmpty() }
            ?: throw IllegalArgumentException(string(R.string.wireguard_invalid_allowed_ips, name, number))
    }
    require(keepalive in 0..65535) { string(R.string.wireguard_invalid_keepalive, name) }
    persistent_keepalive_interval = keepalive.takeIf { it > 0 }
    if (this@serverPeer.reserved.isNotBlank()) {
        reserved = normalizeReserved(this@serverPeer.reserved)
            ?: throw IllegalArgumentException(string(R.string.wireguard_invalid_peer, name, number))
    }
}

private fun WireGuardSettings.extraPeer(section: IniConfig.Section, number: Int) = SingBoxOptions.WireGuardPeer().apply {
    val invalid = { IllegalArgumentException(string(R.string.wireguard_invalid_peer, name, number)) }
    public_key = section["PublicKey"]?.takeIf { it.isNotBlank() } ?: throw invalid()
    pre_shared_key = section["PresharedKey"]?.takeIf { it.isNotBlank() }
    section["Endpoint"]?.let { value ->
        val (host, port) = parseWireGuardEndpoint(value) ?: throw invalid()
        server = host
        server_port = port
    }
    allowed_ips = parseAllowedIPs(section.getAll("AllowedIPs").orEmpty())
        ?.also { require(it.isNotEmpty()) { string(R.string.wireguard_peer_without_allowed_ips, name, number) } }
        ?: throw IllegalArgumentException(string(R.string.wireguard_invalid_allowed_ips, name, number))
    persistent_keepalive_interval = section["PersistentKeepalive"]?.let { parseKeepalive(it) ?: throw invalid() }?.takeIf { it > 0 }
    section["Reserved"]?.let { reserved = normalizeReserved(it) ?: throw invalid() }
}

/**
 * Every peer in configuration order: the additional peers keep their order, and the server peer
 * sits after the first [WireGuardSettings.serverPeerPosition] of them. Peer numbers in errors
 * count in this order, from 1.
 */
internal fun WireGuardSettings.orderedPeers(): List<SingBoxOptions.WireGuardPeer> {
    val sections = extraSections()
    require(serverPeerPosition in 0..sections.size) {
        string(R.string.wireguard_invalid_server_peer_position, name, sections.size)
    }
    val extras = sections.mapIndexed { index, section ->
        extraPeer(section, if (index < serverPeerPosition) index + 1 else index + 2)
    }
    return extras.take(serverPeerPosition) + serverPeer(serverPeerPosition + 1) + extras.drop(serverPeerPosition)
}

/**
 * The peers list, or null while the profile uses none of AllowedIPs, keepalive, further peers or
 * a peer position: such profiles keep the single-peer options they always generated.
 */
internal fun WireGuardSettings.buildPeers(): List<SingBoxOptions.WireGuardPeer>? {
    if (allowedIPs.isBlank() && keepalive == 0 && extraPeers.isBlank() && serverPeerPosition == 0) return null
    return orderedPeers()
}

/**
 * Rejects a WireGuard or AmneziaWG profile that exceeds the bounds or does not parse. Imports, the
 * editor and the config builder all call it, so no path keeps or runs what another refuses.
 */
internal fun AbstractBean.checkWireGuardLimits() {
    val settings = wireGuardSettings() ?: return
    val name = settings.name
    require(KryoConverters.serialize(this).size <= MAX_WIREGUARD_PROFILE_BYTES) { string(R.string.wireguard_too_large, name) }
    val peers = settings.orderedPeers()
    require(peers.size <= MAX_WIREGUARD_PEERS) { string(R.string.wireguard_too_many_peers, name, MAX_WIREGUARD_PEERS) }
    require(peers.sumOf { it.allowed_ips.orEmpty().size } <= MAX_WIREGUARD_ALLOWED_IPS) {
        string(R.string.wireguard_too_many_allowed_ips, name, MAX_WIREGUARD_ALLOWED_IPS)
    }
    for (list in listOf(settings.importedDnsServers, settings.importedDnsDomains, settings.customDnsServers, settings.customDnsDomains)) {
        require(list.listByLineOrComma().size <= MAX_WIREGUARD_DNS_ENTRIES) {
            string(R.string.wireguard_too_many_dns_entries, name, MAX_WIREGUARD_DNS_ENTRIES)
        }
    }
}

private fun prefixContains(prefix: String, address: String): Boolean {
    val network = InetAddress.getByName(prefix.substringBefore('/')).address
    val host = InetAddress.getByName(address).address
    if (network.size != host.size) return false
    val bits = prefix.substringAfter('/').toInt()
    return (0 until bits).all { bit ->
        val mask = 0x80 ushr (bit % 8)
        (network[bit / 8].toInt() and mask) == (host[bit / 8].toInt() and mask)
    }
}

/** Profile DNS of one WireGuard or AmneziaWG outbound in a generated config. */
internal class WireGuardProfileDns(
    val profileId: Long,
    val name: String,
    // Outbound the queries go through.
    val tag: String,
    val mode: Int,
    val server: String,
    val domains: List<String>,
)

/**
 * Validated profile DNS, or null while the profile uses the app DNS. Queries always go through
 * the profile's tunnel, so a missing server or an address no peer accepts is an error rather than
 * a silent detour around it.
 */
internal fun AbstractBean.wireGuardProfileDns(profileId: Long, tag: String): WireGuardProfileDns? {
    val settings = wireGuardSettings() ?: return null
    if (settings.dnsMode == WireGuardDnsMode.APP) return null
    val name = settings.name
    val servers = settings.dnsServers.listByLineOrComma()
    require(servers.isNotEmpty()) { string(R.string.wireguard_dns_missing, name) }
    val allowed = settings.orderedPeers().flatMap { it.allowed_ips.orEmpty() }
    for (server in servers) {
        // The address may carry a DoH path or query; errors name the profile, never the address.
        val host = dnsServerHost(server) ?: throw IllegalArgumentException(string(R.string.wireguard_dns_invalid, name))
        if (host.isIpAddress()) {
            require(allowed.any { prefixContains(it, host) }) { string(R.string.wireguard_dns_outside, name, host) }
        }
    }
    val domains = if (settings.dnsMode == WireGuardDnsMode.DOMAINS) {
        settings.dnsDomains.listByLineOrComma().map {
            parseHostsDomain(it.removePrefix(".")) ?: throw IllegalArgumentException(string(R.string.wireguard_dns_invalid_domain, name))
        }.distinct().also { require(it.isNotEmpty()) { string(R.string.wireguard_dns_domains_missing, name) } }
    } else {
        emptyList()
    }
    return WireGuardProfileDns(profileId, name, tag, settings.dnsMode, servers.first(), domains)
}

fun buildSingBoxOutboundWireguardBean(bean: WireGuardBean): SingBoxOptions.Outbound_WireGuardOptions = SingBoxOptions.Outbound_WireGuardOptions().apply {
    bean.checkWireGuardLimits()
    type = "wireguard"
    local_address = bean.localAddress!!.listByLineOrComma()
    private_key = bean.privateKey
    mtu = bean.mtu
    peers = bean.wireGuardSettings()!!.buildPeers()
    if (peers == null) {
        server = bean.serverAddress
        server_port = bean.serverPort
        peer_public_key = bean.peerPublicKey
        pre_shared_key = bean.peerPreSharedKey
        if (bean.reserved!!.isNotBlank()) reserved = genReserved(bean.reserved!!)
    }
}
